### PR TITLE
Remove useless debug messages

### PR DESCRIPTION
**Pull request by tgagor**
This debug messages are causing problems on systems with multiple network interfaces - look at #32.

### CODE REVIEW

**Comment by juliandunn** [comment]
I think you can also remove the actual `listen_interfaces` attribute if it's not being used elsewhere

**Comment by gagor** [comment]
Done.

**Comment by juliandunn** [comment]
Cool, can you sign the CLA through [supermarket](https://supermarket.chef.io/icla-signatures/new/) so that we can take this?

**Comment by gagor** [comment]
Is it enough to be registered there? Because I'm. 

P. S. It's totally ridiculous that you need this to remove 3 lines from YOUR code, because I didn't write anything there :-)
I'm just wondering what if I will request to remove everything from your cookbook? You won't be able to delete single line because this will broke my copyrights? :-)

**Comment by juliandunn** [comment]
Look, I don't make these legal rules, so there's no need to be snarky. All you have to do is click [this link](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 2 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 2 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by tas50** [comment]
Since the CLA hasn't been signed in over 6 month for this PR I'm going to close it out at this point.  If the author would like to sign the CLA feel free to open up the PR again.

**Pull request closed without merging**
